/**
 * Raster text for ESC/POS printers — the "print the text as an image" engine
 * behind `print_settings.font = "raster:<name>"`.
 *
 * SINGLE SOURCE for both runtimes: the bridge bundles this file; the app
 * imports it too (src/lib/printing/escpos.ts, through raster-text.d.mts), so
 * the two never drift. Keep it dependency-free, plain ESM, browser + Node/Bun.
 *
 * What it does: a line of text (segments with bold / width / height
 * multipliers) is composed from a prebaked 1-bit glyph atlas
 * (bridge/src/fonts/*.atlas.mjs, generated by scripts/print-font-atlas) into
 * one packed bitmap row block, emitted as `GS v 0`, then the paper advances
 * with `ESC J`. The printer only ever burns dots, so every printer prints the
 * same glyphs — no ROM font, no `ESC !`/`ESC M`/`GS !` firmware quirks.
 *
 * Sizes: glyphs are 12×24-dot cells; `wMul`/`hMul` replicate pixels — the
 * same integer magnification the printer applies to its own font, so a
 * "grande" raster ticket keeps the proportions of a "grande" ROM ticket.
 */

const ESC = 0x1b;
const GS = 0x1d;

/** Dots per column at ×1 — `cols × RASTER_CELL_W` is the line width. */
export const RASTER_CELL_W = 12;
/** Paper advance for a blank line when no `ESC 3` spacing is set: the
 *  printer's own 1/6" default (≈34 dots at 203 dpi), i.e. what an LF feeds. */
export const RASTER_DEFAULT_PITCH = 34;
/** Leading under a text line when no `ESC 3` spacing is set — the renderers'
 *  own explicit spacing is `24·h + 8`, so a raster "normal" line advances the
 *  same 56 dots their sized lines do. */
export const RASTER_LINE_LEADING = 8;

/**
 * Same table as escpos.ts: characters the atlas lacks fall back to ASCII
 * look-alikes; anything else prints as "?" — exactly the ROM path's rule, so
 * a raster ticket never shows less than a ROM ticket.
 */
const ASCII_FALLBACK = {
  "—": "-", "–": "-", "−": "-",
  "“": '"', "”": '"', "„": '"', "‟": '"',
  "‘": "'", "’": "'", "‚": "'", "‛": "'",
  "…": "...", "•": "*", "·": ".", "→": "->", "←": "<-",
};

function decodeBase64(b64) {
  if (typeof atob === "function") {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  return new Uint8Array(Buffer.from(b64, "base64"));
}

// face object → Map<char, Uint8Array rows>, decoded lazily and kept for the
// life of the atlas module (one per process; a few KB).
const faceCache = new WeakMap();

function glyphRows(face, ch) {
  let cache = faceCache.get(face);
  if (!cache) {
    cache = new Map();
    faceCache.set(face, cache);
  }
  let rows = cache.get(ch);
  if (rows === undefined) {
    const b64 = face[ch];
    rows = typeof b64 === "string" ? decodeBase64(b64) : null;
    cache.set(ch, rows);
  }
  return rows;
}

/**
 * The characters actually drawn for `s`: atlas hit → itself; else its ASCII
 * fallback (each char resolved again); else "?". Control characters are the
 * engine's business (see `RasterTextEngine.text`), not this function's.
 */
export function normalizeRasterText(font, s) {
  const face = font.faces.regular;
  const out = [];
  for (const ch of s) {
    if (typeof face[ch] === "string") {
      out.push(ch);
      continue;
    }
    const fb = ASCII_FALLBACK[ch];
    if (fb !== undefined) {
      for (const fc of fb) out.push(typeof face[fc] === "string" ? fc : "?");
      continue;
    }
    out.push("?");
  }
  return out;
}

/** Dots on the head for a paper width: 58 mm → 384, 80 mm → 576. */
export function paperDotsForWidth(paperWidthMm) {
  const mm = Number(paperWidthMm);
  return mm > 0 && mm <= 60 ? 384 : 576;
}

/**
 * Compose one line into a packed 1-bit block.
 *
 * @param font      atlas ({ cellW, cellH, faces: { regular, bold } })
 * @param segments  [{ text, bold, wMul, hMul }] in print order
 * @param opts      { lineDots, align, charSpacing }
 * @returns { widthBytes, height, data } — `widthBytes` is trimmed to the last
 *          inked byte column (0 when the line has no ink at all; `height` is
 *          still the line's height so the caller can advance the paper), or
 *          null when there are no segments.
 */
export function composeLine(font, segments, opts) {
  const cellW = font.cellW;
  const cellH = font.cellH;
  const bpr = Math.ceil(cellW / 8);
  const lineDots = Math.max(8, Math.round(opts.lineDots) || 0);
  const align = opts.align ?? "left";
  const spacing = Math.max(0, Math.round(opts.charSpacing ?? 0));

  let lineH = 0;
  let contentW = 0;
  const prepared = [];
  for (const seg of segments) {
    const wMul = Math.max(1, Math.round(seg.wMul) || 1);
    const hMul = Math.max(1, Math.round(seg.hMul) || 1);
    const chars = normalizeRasterText(font, seg.text ?? "");
    prepared.push({ chars, bold: !!seg.bold, wMul, hMul });
    const h = cellH * hMul;
    if (h > lineH) lineH = h;
    contentW += chars.length * (cellW * wMul + spacing);
  }
  if (prepared.length === 0) return null;

  const rowBytes = Math.ceil(lineDots / 8);
  const buf = new Uint8Array(rowBytes * lineH);
  let x =
    align === "center"
      ? Math.floor((lineDots - contentW) / 2)
      : align === "right"
        ? lineDots - contentW
        : 0;
  if (x < 0) x = 0;
  let lastByte = -1;

  for (const seg of prepared) {
    const face = seg.bold ? font.faces.bold : font.faces.regular;
    const gw = cellW * seg.wMul;
    const gh = cellH * seg.hMul;
    const yTop = lineH - gh; // bottom-aligned (baselines meet like on paper)
    for (const ch of seg.chars) {
      if (x >= lineDots) break;
      const rows = glyphRows(face, ch);
      if (rows) {
        for (let gy = 0; gy < gh; gy++) {
          const srcRow = Math.floor(gy / seg.hMul) * bpr;
          const dstRow = (yTop + gy) * rowBytes;
          for (let gx = 0; gx < gw; gx++) {
            const px = x + gx;
            if (px >= lineDots) break;
            const sc = Math.floor(gx / seg.wMul);
            if ((rows[srcRow + (sc >> 3)] >> (7 - (sc & 7))) & 1) {
              const bi = px >> 3;
              buf[dstRow + bi] |= 0x80 >> (px & 7);
              if (bi > lastByte) lastByte = bi;
            }
          }
        }
      }
      x += gw + spacing;
    }
  }

  const widthBytes = lastByte + 1;
  if (widthBytes === 0) return { widthBytes: 0, height: lineH, data: new Uint8Array(0) };
  if (widthBytes === rowBytes) return { widthBytes, height: lineH, data: buf };
  const data = new Uint8Array(widthBytes * lineH);
  for (let r = 0; r < lineH; r++) {
    data.set(buf.subarray(r * rowBytes, r * rowBytes + widthBytes), r * widthBytes);
  }
  return { widthBytes, height: lineH, data };
}

/**
 * Stateful line writer the encoders delegate to in raster mode. Every method
 * that would emit a text-mode command instead updates state; the byte-emitting
 * methods (`text`/`line`/`feed`/`flush`) return plain number arrays the
 * encoder appends to its buffer.
 */
export class RasterTextEngine {
  constructor(font, opts) {
    this.font = font;
    this.lineDots = Math.max(8, Math.round(opts.lineDots) || 0);
    this.alignMode = "left";
    this.bold = false;
    this.wMul = 1;
    this.hMul = 1;
    /** `ESC 3 n` equivalent; 0 = printer default. */
    this.pitch = 0;
    /** `ESC SP n` equivalent, in dots per character. */
    this.spacing = 0;
    this.segments = [];
  }

  align(a) {
    this.alignMode = a === "center" || a === "right" ? a : "left";
  }

  /** `ESC !` semantics: bold bit + double width/height bits; like the hardware
   *  (and the preview decoder) it REPLACES any `GS !` magnification. */
  style(s = {}) {
    this.bold = !!s.bold;
    this.wMul = s.doubleWidth ? 2 : 1;
    this.hMul = s.doubleHeight ? 2 : 1;
  }

  /** `GS !` semantics: replaces the `ESC !` size bits. */
  magnify(w, h) {
    this.wMul = Math.max(1, Math.min(8, Math.round(w) || 1));
    this.hMul = Math.max(1, Math.min(8, Math.round(h) || 1));
  }

  lineSpacing(dots) {
    this.pitch = dots > 0 ? Math.min(255, Math.round(dots)) : 0;
  }

  charSpacing(dots) {
    this.spacing = Math.max(0, Math.min(255, Math.round(dots) || 0));
  }

  /** Buffer text for the current line. A "\n" inside flushes (it is an LF in
   *  text mode); "\t" and "\r" are dropped — they are bytes the ROM path
   *  would swallow as control codes. */
  text(s) {
    const out = [];
    const parts = String(s ?? "").split("\n");
    for (let i = 0; i < parts.length; i++) {
      if (i > 0) pushAll(out, this.flush());
      const t = parts[i].replace(/[\t\r]/g, "");
      if (t) this.segments.push({ text: t, bold: this.bold, wMul: this.wMul, hMul: this.hMul });
    }
    return out;
  }

  line(s = "") {
    const out = s ? this.text(s) : [];
    pushAll(out, this.flush());
    return out;
  }

  feed(n = 1) {
    const out = [];
    for (let i = 0; i < n; i++) pushAll(out, this.blankAdvance());
    return out;
  }

  /** Emit the pending line: a `GS v 0` block (only when it has ink) and the
   *  paper advance that completes the line's footprint. An empty pending
   *  line is a blank line (LF). */
  flush() {
    if (this.segments.length === 0) return this.blankAdvance();
    const composed = composeLine(this.font, this.segments, {
      lineDots: this.lineDots,
      align: this.alignMode,
      charSpacing: this.spacing,
    });
    this.segments = [];
    const H = composed.height;
    // Explicit spacing wins but can never overlap (a raster block always
    // advances its own height); default = glyph height + leading.
    const advance = this.pitch > 0 ? Math.max(this.pitch, H) : H + RASTER_LINE_LEADING;
    const out = [];
    if (composed.widthBytes > 0) {
      out.push(
        GS, 0x76, 0x30, 0x00,
        composed.widthBytes & 0xff, (composed.widthBytes >> 8) & 0xff,
        H & 0xff, (H >> 8) & 0xff,
      );
      pushAll(out, composed.data);
      pushAll(out, this.advanceBytes(advance - H));
    } else {
      pushAll(out, this.advanceBytes(advance));
    }
    return out;
  }

  /** Flush only if something is pending (before a cut / logo / build). */
  flushPending() {
    return this.segments.length ? this.flush() : [];
  }

  blankAdvance() {
    return this.advanceBytes(this.pitch > 0 ? this.pitch : RASTER_DEFAULT_PITCH);
  }

  /** The ONE place paper motion is emitted: `ESC J n` (print and feed n
   *  dots). Swap point if a printer turns out to mishandle it. */
  advanceBytes(dots) {
    const n = Math.max(0, Math.min(255, Math.round(dots)));
    return n > 0 ? [ESC, 0x4a, n] : [];
  }
}

// Loop, never spread: a line block is a few KB and spreading into push()
// would overflow the argument stack on long tickets.
function pushAll(out, bytes) {
  for (let i = 0; i < bytes.length; i++) out.push(bytes[i] & 0xff);
}
